from enum import Enum


class StudyType(Enum):
    EXPERIMENTAL = "EXPERIMENTAL"
    OBSERVATIONAL = "OBSERVATIONAL"
    CROSS_SECTIONAL = "CROSS_SECTIONAL"
    LONGITUDINAL = "LONGITUDINAL"
    CASE_STUDY = "CASE_STUDY"