version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: nasa-backend
    ports:
      - "8000:8000"
    env_file:
      - ./docker/backend/.env
    volumes:
      - ./backend/app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: nasa-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./docker/frontend/.env
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    command: npm run dev -- --host
    depends_on:
      - backend

volumes:
  node_modules:
