from enum import Enum


class Organ(Enum):
    BONE = "BONE"
    MUSCLE = "MUSCLE"
    IMMUNE_SYSTEM = "IMMUNE_SYSTEM"
    NERVOUS_SYSTEM = "NERVOUS_SYSTEM"
    CARDIOVASCULAR_SYSTEM = "CARDIOVASCULAR_SYSTEM"
    RESPIRATORY_SYSTEM = "RESPIRATORY_SYSTEM"
    DIGESTIVE_SYSTEM = "DIGESTIVE_SYSTEM"