from .base_enum import BaseEnum


class SamplingMethod(BaseEnum):
    AIRBORNE_SAMPLING = "Airborne sampling"
    ARCHIVED_SAMPLE_ANALYSIS = "Archived sample analysis"
    CELL_CULTURE_BASED = "Cell culture based"
    CLINICAL_SAMPLE_COLLECTION = "Clinical sample collection"
    COMPUTATIONAL_ANALYSIS = "Computational analysis"
    CONVENIENCE_SAMPLING = "Convenience sampling"
    DATASET_ANALYSIS = "Dataset analysis"
    DUST_PARTICLE_SAMPLING = "Dust particle sampling"
    ENVIRONMENTAL_SURFACE_SAMPLING = "Environmental surface sampling"
    FIELD_SAMPLING = "Field sampling"
    FORWARD_GENETIC_SCREENING = "Forward genetic screening"
    GROUND_CONTROL_SIMULATION = "Ground control simulation"
    ISOLATE_COLLECTION = "Isolate collection"
    LONGITUDINAL_SAMPLING = "Longitudinal sampling"
    METAGENOMIC_SAMPLING = "Metagenomic sampling"
    MINIMALLY_INVASIVE_BIOPSY = "Minimally invasive biopsy"
    MUTANT_GENERATION_AND_SCREENING = "Mutant generation and screening"
    OBSERVATIONAL_STUDY = "Observational study"
    PLANT_SAMPLE_COLLECTION = "Plant sample collection"
    RANDOM_ALLOCATION_OR_ASSIGNMENT = "Random allocation or assignment"
    RANDOM_SAMPLING = "Random sampling"
    RE_ANALYSIS_OF_EXISTING_DATA = "Re-analysis of existing data"
    ROUTINE_OMICS_COLLECTION = "Routine omics collection"
    SOLID_PHASE_EXTRACTION = "Solid phase extraction"
    SPACECRAFT_SURFACE_SAMPLING = "Spacecraft surface sampling"
    STERILE_WIPE_SAMPLING = "Sterile wipe sampling"
    SURFACE_SEDIMENT_CORE_SAMPLING = "Surface sediment core sampling"
    SWAB_SAMPLING = "Swab sampling"
    TISSUE_SAMPLE_COLLECTION = "Tissue sample collection"
    WATER_SAMPLE_COLLECTION = "Water sample collection"
